services:
  rabbitmq:
    image: rabbitmq:4-management
    environment:
      - "RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost"
    ports:
      - "5552:5552"
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro"