spring.application.name=demo
#spring.kotlinx.serialization.json.allow-comments=false
#spring.kotlinx.serialization.json.ignore-unknown-keys=true
#spring.kotlinx.serialization.json.naming-strategy=snake_case
#spring.kotlinx.serialization.json.explicit-nulls=false
#spring.kotlinx.serialization.json.encode-defaults=true
#spring.kotlinx.serialization.json.pretty-print=true
