spring.application.name=demo
logging.level.root=INFO
logging.level.com.example.demo=DEBUG

logging.level.org.springframework.kafka.core.KafkaTemplate=ERROR

#spring.kafka.bootstrap-servers=localhost:9092
#
#consumer config for Spring Kafka
#
#spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=demo-group
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
#spring.kafka.consumer.properties[spring.json.value.default.type]=com.example.demo.WordCount
spring.kafka.consumer.properties[spring.json.trusted.packages]=*
#
# producer config
#
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
#spring.kafka.producer.properties[spring.json.add.type.headers]=true
#spring.kafka.producer.properties[spring.json.trusted.packages]=com.example,org.acme

#
# Kafka streams config
#
# fallback is spring.application.name
spring.kafka.streams.application-id=demo
#spring.kafka.streams.properties[default.key.serde]=org.apache.kafka.common.serialization.Serdes.StringSerde
#spring.kafka.streams.properties[default.value.serde]=org.apache.kafka.common.serialization.Serdes.IntegerSerde