spring.application.name=demo
logging.level.root=INFO
logging.level.com.example.demo=DEBUG

logging.level.org.springframework.kafka.core.KafkaTemplate=ERROR

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.properties.session.timeout.ms=45000
#
# consumer config for Spring Kafka
#
#spring.kafka.consumer.group-id=demo-group
#spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.LongDeserializer
#spring.kafka.consumer.properties[spring.json.trusted.packages]=*
#
# producer config
#
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.client-id=demo-producer
#
# Kafka streams config
#
# fallback is spring.application.name
spring.kafka.streams.application-id=demo-app
#spring.kafka.streams.replication-factor=3


