spring.application.name=demo
logging.level.root=INFO
logging.level.web=DEBUG
logging.level.com.example.demo=DEBUG
spring.http.reactiveclient.connect-timeout=3s
spring.http.reactiveclient.read-timeout=1s
spring.http.reactiveclient.redirects=dont_follow

# requires Jetty reactive http client in the classpath.
#spring.http.reactiveclient.connector=jetty