spring.application.name=demo
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.level.org.apache.kafka=warn
logging.level.org.springframework.kafka.core.KafkaTemplate=ERROR

spring.kafka.bootstrap-servers=localhost:9092