spring.application.name=demo
logging.level.root=INFO
logging.level.web=DEBUG
logging.level.com.example.demo=DEBUG

#spring.http.client.connect-timeout=3s
#spring.http.client.read-timeout=2s
#spring.http.client.redirects=dont_follow

spring.http.serviceclient[post].baseUrl=http://localhost:9090
