spring.application.name=demo
logging.level.root=INFO
logging.level.web=DEBUG
logging.level.com.example.demo=DEBUG
spring.http.clients.connect-timeout=3s
spring.http.clients.read-timeout=2s
spring.http.clients.redirects=dont_follow