spring.application.name=demo
logging.level.root=INFO
logging.level.sql=DEBUG
logging.level.com.example=DEBUG
spring.sql.init.mode=always 

#spring.datasource.vibur.jdbc-url=jdbc:postgresql://localhost:5432/testdb
#spring.datasource.vibur.username=user
#spring.datasource.vibur.password=passowrd
#spring.datasource.vibur.driver-class-name=