name: boot-data-couchbase

on:
  push:
    paths:
      - "boot-data-couchbase/**"
    branches:
      - master
  pull_request:
    paths:
      - "boot-data-couchbase/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25
          cache: "maven"

      - name: Build with Maven
        run: mvn -B -q clean package --file boot-data-couchbase/pom.xml
        

